name: Build MoCA Agent Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-entservices-on-pr:
    name: Build moca-agent component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          sh -x cov_docker_script/setup_dependencies.sh
          sh -x cov_docker_script/build_native.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
